# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Angela (InJu) Yoon
# title: "Work Permit: US Citizen"
email: dlswn35@gmail.com
# website: www.github.com/sproogen/resume-theme


# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Angela118
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: angela-yoon94
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/grad.jpg
about_content: | # this will include new lines to allow paragraphs
  Dedicated computer science professional specializing in software development, with a strong interest in data analysis. Able to collaborate effectively, with strong interpersonal skills and proficiency in various programming languages.
  
  Work Permit: <mark>KOR/US dual-citizenship</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: University of California, Davis
        caption: Jun 2023
        sub_title: Master of Science in Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      
      - layout: top
        title: Sookmyung Women's University
        caption: Feb 2020
        sub_title: Bachelor of Engineering in Computer Science

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Programming Languages and Tools: Python, C/C++, Java, JavaScript, SQL, MongoDB, Node.js, Arduino, App Inventor
      - Data Analysis Tool: Pandas, Scikit-learn, Numpy, Seaborn, Matplotlib

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Research about Gamification in AI Education
        sub_title: Advised by Prof.Setareh Rafatirad
        # link: github.com/sproogen
        # link_text: Project Website
        caption: Mar 2023 - Sep 2023
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This project aims to create an innovative gamification framework that leverages machine learning to promote equity and inclusion in the education field.
        description: | # this will include new lines to allow paragraphs
          - Collected and cleaned data performing in-depth analysis of 35 commercially available and playable educational games designed for teaching AI across 18 criteria and built a comprehensive data set.
          - Conducted exploratory research using Python libraries to visualize and analyze the data distributions and correlations
          - <mark>Python</mark> <mark>Pandas</mark>, <mark>Numpy</mark>, <mark>Seaborn</mark>, <mark>Matplotlib</mark>
      
      - layout: top
        title: “Play Meet”
        link: github.com/Angela118/playmeet
        # link_text: Project Website
        caption: May 2018 - Sep 2018
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “Play Meet” is an unreleased web application that helps amateur soccer teams find the most ideal opponent team. This application includes several functions such as messenger, scheduling with a calendar, reviewing the opposing team, and recommendation systems.
        description: | # this will include new lines to allow paragraphs
          - As the team leader of a three-member team, managed and optimized the entire project workflow, ensuring operational efficiency and culminating in a successful final presentation.
          - Developed the recommendation system using Numpy and SciPy, leveraging Euclidean distance to analyze user information data for personalized recommendations.
          - Built the database to store and manage user information, chat logs, reviews, and schedules.
          - Engineered the server to handle the data for the match management system, posting games, chatting, scheduling, and reviews.
          - <mark>Python</mark>, <mark>JavaScript</mark>, <mark>Node.js</mark>, <mark>MongoDB</mark>

      - layout: top
        title: "WIC Maker Hackathon: “IoT Smart Stroller”"
        # link: github.com/Angela118/playmeet
        # link_text: Project Website
        caption: Jan 2018
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “IoT Smart Stroller” which can read the surroundings and react optimally for parents.
        description: | # this will include new lines to allow paragraphs
          - As the leader of a five-member team, led the project and team, adeptly managing constraints that required us to utilize a limited set of tools within a designated time frame.
          - Coded several Arduino sensors (the distance, bump, temperature and humidity, and sound sensors) and a speaker which were attached to the stroller.
          - Developed a simple mobile application to display data from the sensors for users by connecting it to the Arduino system.
          - <mark>App Inventor</mark>, <mark>Arduino</mark>

  - title: Activities # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Data Science Immersive Program
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: BOOSTCOURSE '<Data Science Projects 2024>' Coaching Study
        caption: Jan 2024 - Feb 2024
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Analyzed multiple datasets on Kaggle, performing Exploratory Data Analysis (EDA), Feature Engineering, Model Selection, and Parameter Optimization using Python-based techniques.
      
      - layout: top
        title: AI Immersive Program
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: BOOSTCOURSE Coaching Study '<Let's AI>'
        caption: May 2024 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #     Analyzed multiple datasets on Kaggle, performing Exploratory Data Analysis (EDA), Feature Engineering, Model Selection, and Parameter Optimization using Python-based techniques.

  - title: Honor & Scholarships
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 3rd place, WIC Maker Hackathon        @Sookmyung Women't University
      - Honor Student Scholarship       @Sookmyung Women’s University
      - Prime Scholarship       @Sookmyung Women’s University

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: University of California, Davis
  #       caption: Jun 2023
  #       sub_title: Master of Science in Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: Skills
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     - Programming skills: Python,  Java, C, C++, JavaScript, SQL, MongoDB, Arduino
  #     - Data Analysis using Python with Pandas, Scikit-learn, Numpy, Seaborn, and Matplotlib.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag